name: CI Tests

on:
  #push:
   # branches: [develop, feature/*, hotfix/*]
  pull_request:
    branches: [main, develop, release/*]

jobs:
  nf-test:
    runs-on: ubuntu-latest

    env:
      NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
      NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Nextflow 25.04
        uses: nf-core/setup-nextflow@v2
        with:
          version: "25.04"

      - name: Setup nf-test 0.9.2
        uses: nf-core/setup-nf-test@v1
        with:
          version: 0.9.2
          install-pdiff: true

      - name: Set up apptainer
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt update
          sudo apt install -y apptainer apptainer-suid
          mkdir -p $NXF_SINGULARITY_CACHEDIR
          mkdir -p $NXF_SINGULARITY_LIBRARYDIR

      - name: Run Tests - Only Changed
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          BASE=${{ github.event.pull_request.base.sha }}
          NFT_WORKDIR=~

          nf-test test \
              --profile test \
              --tap=test.tap \
              --ci \
              --verbose \
              --tag=local \
              --filter=process,workflow \
              --changed-since="$BASE"

          echo "tap_file_path=$(realpath test.tap)" >> $GITHUB_OUTPUT

      - name: Run Tests - Pipeline
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          NFT_WORKDIR=~

          nf-test test \
              --profile test \
              --tap=test.tap \
              --ci \
              --verbose \
              --tag=pipeline/local

          echo "tap_file_path=$(realpath test.tap)" >> $GITHUB_OUTPUT

      - name: Clean up
        if: always()
        shell: bash
        run: |
          sudo rm -rf /home/ubuntu/tests/
